version: '3'
services:
  portainer:
    image: portainer/portainer-ce:2.11.1
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      - "traefik.enable=true"
      
      - "traefik.http.routers.portainer_https.entrypoints=websecure"
      - "traefik.http.routers.portainer_https.rule=Host(`portainer.joost.io`)"
      - "traefik.http.routers.portainer_https.tls=true"
      - "traefik.http.routers.portainer_https.tls.certresolver=myresolver"
      - "traefik.http.routers.portainer_https.service=portainer"

      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

      - "traefik.http.routers.portainer_http.entrypoints=web"
      - "traefik.http.routers.portainer_http.rule=Host(`portainer.joost.io`)"
      - "traefik.http.routers.portainer_http.middlewares=https_redirect"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"
    networks:
      - traefik

volumes:
  portainer_data:

networks:
  traefik:
    external: true